name: php-pecl-libsodium
profiles:
  php56w:
    define:
      basepkg: php56w
  php70w:
    define:
      basepkg: php70w
  php71w:
    define:
      basepkg: php71w
  php72w:
    define:
      basepkg: php72w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
    profiles:
      - php56w
      - php70w
      - php71w
      - php72w
